# Generated by Django 4.2.4 on 2023-10-06 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название урока')),
                ('video_url', models.URLField(unique=True, verbose_name='ссылка на видео урока')),
                ('length', models.PositiveSmallIntegerField(verbose_name='продолжительность урока (сек.)')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='название продукта')),
                ('owners', models.ManyToManyField(blank=True, related_name='products_owned', to=settings.AUTH_USER_MODEL, verbose_name='владельцы продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='LessonWatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_watched', models.PositiveSmallIntegerField(default=0, verbose_name='просмотрено (сек.)')),
                ('last_watched', models.DateField(blank=True, null=True, verbose_name='дата последнего просмотра')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_stats', to='products.lesson', verbose_name='урок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_stats', to='products.product', verbose_name='продукт')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_stats', to=settings.AUTH_USER_MODEL, verbose_name='студент')),
            ],
            options={
                'verbose_name': 'данные о просмотре урока',
                'verbose_name_plural': 'данные о просмотрах уроков',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='associated_products',
            field=models.ManyToManyField(related_name='lessons_included', to='products.product', verbose_name='находится в продуктах'),
        ),
        migrations.AddConstraint(
            model_name='lessonwatchdata',
            constraint=models.UniqueConstraint(fields=('student', 'product', 'lesson'), name='unique_lesson_in_product_for_student'),
        ),
    ]
